# Generated by Django 3.1.4 on 2020-12-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, upload_to='issue_images'),
        ),
        migrations.DeleteModel(
            name='IField',
        ),
    ]
