# Generated by Django 3.1.4 on 2020-12-20 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0005_auto_20201220_0617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisLike',
            new_name='CDisLike',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='CLike',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='likes',
        ),
        migrations.CreateModel(
            name='ILike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='issues.issue')),
                ('users', models.ManyToManyField(related_name='requirement_issue_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='issues.issue')),
                ('users', models.ManyToManyField(related_name='requirement_issue_dis_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
