# Generated by Django 3.1.4 on 2020-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20201220_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_newspaper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
